Synchronize the install and update scripts of flippy

diff --git a/luci-app-amlogic/root/usr/sbin/openwrt-backup b/luci-app-amlogic/root/usr/sbin/openwrt-backup
--- a/luci-app-amlogic/root/usr/sbin/openwrt-backup
+++ b/luci-app-amlogic/root/usr/sbin/openwrt-backup
@@ -5,6 +5,7 @@
 # Copyright (C) 2020 https://github.com/lasthinker/amlogic-s9xxx-openwrt
 #======================================================================
 
+VERSION="v1.1"
 SNAPSHOT_PRESTR=".snapshots/"
 BACKUP_DIR="/.reserved"
 BACKUP_NAME="openwrt_config.tar.gz"
@@ -17,8 +18,8 @@ BACKUP_LIST='./etc/AdGuardHome.yaml \
 ./etc/smbd/smbdpwd.db \
 ./etc/ksmbd/ksmbdpwd.db \
 ./etc/config/ \
+./usr/share/openclash/core/ \
 ./etc/openclash/backup/ \
-./etc/openclash/core/ \
 ./etc/openclash/config/ \
 ./etc/openclash/custom/ \
 ./etc/openclash/game_rules/ \
@@ -30,7 +31,7 @@ BACKUP_LIST='./etc/AdGuardHome.yaml \
 ./etc/dnsmasq.oversea/ \
 ./etc/dnsmasq.ssr/ \
 ./etc/docker/key.json \
-./etc/dropbear/dropbear_rsa_host_key \
+./etc/dropbear/ \
 ./etc/easy-rsa/ \
 ./etc/environment \
 ./etc/ethers \
@@ -55,10 +56,14 @@ BACKUP_LIST='./etc/AdGuardHome.yaml \
 ./etc/shadow \
 ./etc/smartdns/ \
 ./etc/sqm/ \
+./etc/ssh/*key*  \
 ./etc/ssl/private/  \
 ./etc/ssrplus/ \
 ./etc/transmission/ \
-./etc/urandom.seed'
+./etc/uhttpd.crt \
+./etc/uhttpd.key \
+./etc/urandom.seed \
+./root/.ssh/'
 
 if dmesg | grep 'meson' >/dev/null 2>&1; then
     PLATFORM="amlogic"
@@ -85,8 +90,10 @@ backup() {
 restore() {
     EMMC_NAME=$(lsblk | grep -oE '(mmcblk[0-9])' | sort | uniq)
     [ -d "${BACKUP_DIR}" ] || mkdir -p "${BACKUP_DIR}"
-    [ -f "/tmp/upload/${BACKUP_NAME}" ] && mv -f "/tmp/upload/${BACKUP_NAME}" ${BACKUP_FILE} && sync
-    [ -f "/mnt/${EMMC_NAME}p4/${BACKUP_NAME}" ] && mv -f "/mnt/${EMMC_NAME}p4/${BACKUP_NAME}" ${BACKUP_FILE} && sync
+    [ -f "/tmp/upload/${BACKUP_NAME}" ] && mv -f "/tmp/upload/${BACKUP_NAME}" ${BACKUP_FILE}
+    [ -f "/mnt/${EMMC_NAME}p4/${BACKUP_NAME}" ] && mv -f "/mnt/${EMMC_NAME}p4/${BACKUP_NAME}" ${BACKUP_FILE}
+    [ -f "/mnt/${EMMC_NAME}p4/.tmp_upload/${BACKUP_NAME}" ] && mv -f "/mnt/${EMMC_NAME}p4/.tmp_upload/${BACKUP_NAME}" ${BACKUP_FILE}
+    sync
 
     if [ -f "${BACKUP_FILE}" ]; then
         echo -n "restore config files ... "
@@ -296,6 +303,128 @@ delete_snapshot() {
     fi
 }
 
+migrate_snapshot() {
+    cur_rootdev=$(lsblk -l -o NAME,MOUNTPOINT |awk '$2~/^\/$/ {print $1}')
+    if [ "$cur_rootdev" == "" ];then
+        echo "Cannot find the disk device corresponding to the current rootfs！"
+        read -p "Press enter to return" q
+        return
+    fi
+    dev_pre=$(echo "$cur_rootdev" | awk '{print substr($1, 1, length($1)-1);}')
+    rootdev_idx=$(echo "$cur_rootdev" | awk '{print substr($1, length($1),1);}')
+    case $rootdev_idx in
+        2)  old_rootpath="/mnt/${dev_pre}3";;
+        3)  old_rootpath="/mnt/${dev_pre}2";;
+        *)  echo "Failed to select the rootfs path of the old version!"
+            read -p "Press enter to return" q
+            return
+            ;;
+    esac
+    echo "The following is a snapshot of etc found from the old version of rootfs, please enter the name of one of them"
+    echo "Tips: Automatically exclude etc-000 and etc-001"
+    echo "-----------------------------------------------------------------------------------"
+    btrfs subvolume list -rt "$old_rootpath" | grep -v "${SNAPSHOT_PRESTR}etc-000" | grep -v "${SNAPSHOT_PRESTR}etc-001"
+    echo "-----------------------------------------------------------------------------------"
+    read -p "Please enter the name of the snapshot to be migrated (just enter ${SNAPSHOT_PRESTR} after the part): " old_snap_name
+    if [ "$old_snap_name" == "" ];then
+        read -p "The name is empty, press enter to return" q
+        return
+    elif ! btrfs subvolume list -rt "$old_rootpath" | awk '{print $4}' | grep "^${SNAPSHOT_PRESTR}${old_snap_name}$" >/dev/null;then
+        echo "The name was entered incorrectly, and the corresponding snapshot was not found!"
+        read -p "Press enter to return" q
+        return
+    elif [ "$old_snap_name" == "etc-000" ] || [ "$old_snap_name" == "etc-001" ];then
+        echo "Critical snapshots are not allowed to migrate!"
+        read -p "Press enter to return" q
+        return
+    fi
+
+    # Find out if there is a snapshot with the same name under the current rootfs
+    if btrfs subvolume list -rt / | awk '{print $4}' | grep "^\\${SNAPSHOT_PRESTR}${old_snap_name}$" >/dev/null;then
+        echo "The existing name is [$old_snap_name] Snapshot of, cannot be migrated!"
+        read -p "Press enter to return" q
+        return
+    fi
+
+    need_size=$(du -h -d0 ${old_rootpath}/${SNAPSHOT_PRESTR}${old_snap_name} | tail -n1 | awk '{print $1}')
+    echo "----------------------------------------------------------------------------------------------"
+    df -h
+    echo "----------------------------------------------------------------------------------------------"
+    echo -e "\033[1mNote: Migration [${old_rootpath}] Snapshot [$old_snap_name] To the present rootfs, Need to take up about $need_size space,"
+    echo -e "      please confirm [/] Partition [/dev/${cur_rootdev}] Available space(Available)Is it sufficient?\033[0m"
+    read -p "Are you sure to migrate? y/n [n] " yn
+    if [ "$yn" == "y" ] ||  [ "$yn" == "Y" ];then
+        (
+            cd /
+            btrfs send ${old_rootpath}/${SNAPSHOT_PRESTR}${old_snap_name} | btrfs receive ${SNAPSHOT_PRESTR}
+            if [ $? -eq 0 ];then
+                btrfs property set -ts ${SNAPSHOT_PRESTR}${old_snap_name} ro false
+                cp ${SNAPSHOT_PRESTR}etc-000/config/fstab ${SNAPSHOT_PRESTR}${old_snap_name}/config/
+                cp ${SNAPSHOT_PRESTR}etc-000/fstab ${SNAPSHOT_PRESTR}${old_snap_name}/
+                cp ${SNAPSHOT_PRESTR}etc-000/openwrt_release ${SNAPSHOT_PRESTR}${old_snap_name}/
+                cp ${SNAPSHOT_PRESTR}etc-000/openwrt_version ${SNAPSHOT_PRESTR}${old_snap_name}/
+                cp ${SNAPSHOT_PRESTR}etc-000/flippy-openwrt-release ${SNAPSHOT_PRESTR}${old_snap_name}/
+                cp ${SNAPSHOT_PRESTR}etc-000/banner ${SNAPSHOT_PRESTR}${old_snap_name}/banner
+                btrfs property set -ts ${SNAPSHOT_PRESTR}${old_snap_name} ro true
+                echo "The migration is complete, if you want to apply the snapshot [$old_snap_name], Please use the restore snapshot function."
+            else
+                echo "Migration failed!"
+            fi
+            read -p "Press enter to return" q
+            return
+        )
+    fi
+}
+
+snapshot_help() {
+    clear
+    cat <<EOF
+============================================================================================================
+1.  What is a snapshot?
+    A snapshot is the state record of a certain subvolume at a certain point in time, and a snapshot is a
+    special subvolume；
+    When the local snapshot is first generated, it shares the disk space with the original subvolume, so it
+    does not occupy additional space, and only the files that have changed subsequently occupy space；
+    Snapshots migrated from other places are not snapshots in essence, but just ordinary subvolumes, so they
+    take up space.
+2.  How to display existing snapshots?
+    input the command： btrfs subvolume list -rt /
+---------------------------------------------------------------------------------------------
+EOF
+    btrfs subvolume list -rt /
+    cat <<EOF
+---------------------------------------------------------------------------------------------
+2.  How to create a snapshot?
+    btrfs subvolume snapshot -r /etc /.snapshots/Snapshot1  # -r It means to generate a read-only snapshot
+3.  How to delete a snapshot?
+    btrfs subvolume delete -c /.snapshots/Snapshot1  # -c Yes commit the meaning of
+4.  How to rename a snapshot?
+    Just use the mv command of the operating system, for example：
+    mv /.snapshots/Snapshot1 /.snapshots/Snapshot2
+5.  How to restore the snapshot?
+    mv /etc /etc.backup  # Back up etc to etc.backup, that is, rename the subvolume
+    btrfs subvolume snapshot /.snapshots/etc-001  /etc   # Use snapshot etc-001 to generate snapshot etc.
+    Note that there is no -r parameter
+    # (Yes, snapshots can also be regenerated)
+    btrfs delete -c /etc.backup # After the previous step is successful, just delete the etc backup just now
+6.  How to restore a file from a snapshot?
+    Example A: Restore mount point configuration file from snapshot etc-000： /etc/config/fstab
+        cp /.snapshots/etc-000/config/fstab /etc/config/
+    Example B: Restore network configuration from snapshot etc-001：
+        cp /.snapshots/etc-001/config/network  /etc/config/
+    Example C: Restore ssr configuration file from snapshot etc-001：
+        cp /.snapshots/etc-001/config/shadowsocksr /etc/config/
+    # (Yes, it is the copy command of the operating system)
+7.  How to migrate snapshots from remote?
+    btrfs support ssh Remote migration of snapshots, E.g:
+    ssh 192.168.2.1 btrfs send /.snapshots/SnapshotX  |  btrfs receive /.snapshots
+    After the command is completed, the remote SnapshotX is copied to the local /.snapshots/SnapshotX
+    (as mentioned above, the migration is a subvolume, which will take up space)
+============================================================================================================
+EOF
+    exit 0
+}
+
 print_help() {
     echo "Usage: $0  -b    [ backup ]"
     echo "       $0  -r    [ restore ]"
@@ -326,8 +455,10 @@ menu() {
         │                                 │
         │       l. list snapshots         │
         │       c. create snapshot        │
-        │       s. restore snapshot       │
         │       d. delete snapshot        │
+        │       R. restore snapshot       │
+        │       m. migrate snapshot       │
+        │       s. snapshot help          │
         │                                 │
         ╞═════════════════════════════════╡
         │                                 │
@@ -347,15 +478,17 @@ EOF
             p | print_list)        print_list;;
             l | list_snapshot)     list_snapshot;;
             c | create_snapshot)   create_snapshot;;
-            s | restore_snapshot)  restore_snapshot;;
             d | delete_snapshot)   delete_snapshot;;
+            R | restore_snapshot)  restore_snapshot;;
+            m | migrate_snapshot)  migrate_snapshot;;
+            s | snapshot_help)     snapshot_help;;
             h | help)              print_help;;
             q | quit)              exit 0;;
         esac
     done
 }
 
-getopts 'brgplcsdhq' opts
+getopts 'brgplcRmsdhq' opts
 case $opts in 
     b | backup)            backup;;
     r | restore)           restore
@@ -364,8 +497,10 @@ case $opts in
     p | print_list)        print_list;;
     l | list_snapshot)     list_snapshot;;
     c | create_snapshot)   create_snapshot;;
-    s | restore_snapshot)  restore_snapshot;;
     d | delete_snapshot)   delete_snapshot;;
+    R | restore_snapshot)  restore_snapshot;;
+    m | migrate_snapshot)  migrate_snapshot;;
+    s | snapshot_help)     snapshot_help;;
     h | help)              print_help;;
     q | quit)              exit 0;;
     *)                     menu;;
